### ISSUE TITLE
GitlCI execution fails with image: jtim/docker-docker-compose-jdk-mvn as it does not contain jq 

### ISSUE THREAD

**Issue by minalbidave** [j-tim/docker-docker-compose-jdk-mvn#6]
Tried to add jq in before_script section but did not work. It fails with below error

$ apk add --update jq 
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied

**Comment by j-tim** [comment]
Thanks @minalbidave for reporting the issue.
It's correct you run into this issue. The image is designed to run as non root.

```
docker run -it jtim/docker-docker-compose-jdk-mvn bash
bash-4.4$ id
uid=1000(bob-the-builder) gid=1000(bob-the-builder) groups=1000(bob-the-builder)
bash-4.4$ apk add --update jq
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```

Because `bob-the-builder` isn't root, this user can't install any additional software like jq.
But I see the value of having jq in this image. I'll create a new image with jq see #7  

Let me know in case you need additional tools that make sense to include.

**Comment by j-tim** [comment]
The latest Java 8, Maven 3.6.3 version of the Docker image now contains `jq`

```
jtim/docker-docker-compose-jdk-mvn:20.10.2-compose-1.28.0-openjdk-8u252-maven-3.6.3
```

@minalbidave can you give it a try in your pipeline?

**Comment by minalbidave** [comment]
@j-tim Sure, I'll give it a try.

**Comment by j-tim** [comment]
👍

**Comment by minalbidave** [comment]
@j-tim It works perfectly fine now. Thanks :)

**Comment by j-tim** [comment]
That's great. I'll close this ticket.
